import { productImages } from "./images";

export interface Product {
  id: string;
  name: string;
  slug: string;
  sku: string;
  category: string;
  subcategory: string;
  brand: string;
  price: number;
  originalPrice?: number;
  discount?: number;
  stock: number;
  status: "in_stock" | "coming_soon" | "out_of_stock";
  image: string;
  shortDesc: string;
  tags: string[];
  featured: boolean;
  bestSeller: boolean;
  showOnHome: boolean;
  specs?: Record<string, string>;
}

const img = productImages;

const defaultProducts: Product[] = [
  // LAPTOPS
  { id: "l1", name: "Laptop Acer Aspire 5 A515-58M", slug: "acer-aspire-5-a515", sku: "LA-LT-001", category: "laptop", subcategory: "laptop-van-phong", brand: "Acer", price: 12990000, originalPrice: 14990000, discount: 13, stock: 15, status: "in_stock", image: img.laptop1, shortDesc: "Intel Core i5-1335U, 8GB RAM, 512GB SSD, 15.6\" FHD IPS", tags: ["bán chạy"], featured: true, bestSeller: true, showOnHome: true, specs: { CPU: "Intel Core i5-1335U", RAM: "8GB DDR4", "Ổ cứng": "512GB NVMe SSD", "Màn hình": "15.6\" FHD IPS" } },
  { id: "l2", name: "Laptop ASUS VivoBook 15 OLED", slug: "asus-vivobook-15-oled", sku: "LA-LT-002", category: "laptop", subcategory: "laptop-van-phong", brand: "ASUS", price: 15490000, originalPrice: 17490000, discount: 11, stock: 8, status: "in_stock", image: img.laptop1, shortDesc: "Intel Core i7-1355U, 16GB RAM, 512GB SSD, OLED 15.6\"", tags: ["mới"], featured: true, bestSeller: false, showOnHome: true, specs: { CPU: "Intel Core i7-1355U", RAM: "16GB DDR4", "Ổ cứng": "512GB NVMe SSD", "Màn hình": "15.6\" OLED FHD" } },
  { id: "l3", name: "Laptop Lenovo IdeaPad Slim 3", slug: "lenovo-ideapad-slim-3", sku: "LA-LT-003", category: "laptop", subcategory: "laptop-hoc-tap", brand: "Lenovo", price: 9990000, stock: 20, status: "in_stock", image: img.laptop3, shortDesc: "AMD Ryzen 5 7520U, 8GB RAM, 256GB SSD, 15.6\" FHD", tags: [], featured: false, bestSeller: true, showOnHome: true, specs: { CPU: "AMD Ryzen 5 7520U", RAM: "8GB", "Ổ cứng": "256GB SSD", "Màn hình": "15.6\" FHD" } },
  { id: "l4", name: "Laptop HP Victus 15 Gaming", slug: "hp-victus-15-gaming", sku: "LA-LT-004", category: "laptop", subcategory: "laptop-gaming", brand: "HP", price: 18990000, originalPrice: 21990000, discount: 14, stock: 5, status: "in_stock", image: img.laptopGaming, shortDesc: "Intel Core i5-13420H, RTX 3050, 8GB RAM, 512GB SSD", tags: ["giảm giá", "bán chạy"], featured: true, bestSeller: true, showOnHome: true, specs: { CPU: "Intel Core i5-13420H", VGA: "RTX 3050 4GB", RAM: "8GB DDR4", "Ổ cứng": "512GB SSD" } },
  { id: "l5", name: "Laptop MSI Katana 15 B13VFK", slug: "msi-katana-15", sku: "LA-LT-005", category: "laptop", subcategory: "laptop-gaming", brand: "MSI", price: 27990000, originalPrice: 29990000, discount: 7, stock: 3, status: "in_stock", image: img.laptopGaming, shortDesc: "Intel Core i7-13620H, RTX 4060, 16GB RAM, 512GB SSD", tags: ["mới"], featured: true, bestSeller: false, showOnHome: true, specs: { CPU: "Intel Core i7-13620H", VGA: "RTX 4060 8GB", RAM: "16GB DDR5", "Màn hình": "15.6\" FHD 144Hz" } },
  { id: "l6", name: "Laptop Dell Latitude 5540", slug: "dell-latitude-5540", sku: "LA-LT-006", category: "laptop", subcategory: "laptop-van-phong", brand: "Dell", price: 22990000, stock: 4, status: "in_stock", image: img.laptop1, shortDesc: "Intel Core i7-1365U, 16GB RAM, 512GB SSD, 15.6\" FHD", tags: [], featured: false, bestSeller: false, showOnHome: true, specs: { CPU: "Intel Core i7-1365U", RAM: "16GB DDR5", "Ổ cứng": "512GB SSD" } },
  { id: "l7", name: "MacBook Air M2 2024", slug: "macbook-air-m2-2024", sku: "LA-LT-007", category: "laptop", subcategory: "macbook", brand: "Apple", price: 24990000, originalPrice: 27990000, discount: 11, stock: 6, status: "in_stock", image: img.laptop3, shortDesc: "Apple M2, 8GB RAM, 256GB SSD, 13.6\" Liquid Retina", tags: ["giảm giá"], featured: true, bestSeller: true, showOnHome: true, specs: { CPU: "Apple M2", RAM: "8GB", "Ổ cứng": "256GB SSD", "Màn hình": "13.6\" Liquid Retina" } },
  { id: "l8", name: "Laptop ASUS TUF Gaming F15", slug: "asus-tuf-gaming-f15", sku: "LA-LT-008", category: "laptop", subcategory: "laptop-gaming", brand: "ASUS", price: 21490000, originalPrice: 23990000, discount: 10, stock: 7, status: "in_stock", image: img.laptopGaming, shortDesc: "Intel Core i5-12500H, RTX 4050, 8GB RAM, 512GB SSD", tags: ["bán chạy"], featured: false, bestSeller: true, showOnHome: true, specs: { CPU: "Intel Core i5-12500H", VGA: "RTX 4050 6GB", RAM: "8GB DDR4" } },
  { id: "l9", name: "Laptop HP ProBook 450 G10", slug: "hp-probook-450", sku: "LA-LT-009", category: "laptop", subcategory: "laptop-van-phong", brand: "HP", price: 16990000, stock: 10, status: "in_stock", image: img.laptop1, shortDesc: "Intel Core i5-1335U, 8GB RAM, 512GB SSD, 15.6\" FHD", tags: [], featured: false, bestSeller: false, showOnHome: true, specs: { CPU: "Intel Core i5-1335U", RAM: "8GB DDR4", "Ổ cứng": "512GB SSD" } },
  { id: "l10", name: "Laptop Lenovo ThinkPad E16 Gen 1", slug: "lenovo-thinkpad-e16", sku: "LA-LT-010", category: "laptop", subcategory: "laptop-do-hoa", brand: "Lenovo", price: 19990000, originalPrice: 22490000, discount: 11, stock: 4, status: "in_stock", image: img.laptop1, shortDesc: "Intel Core i7-1355U, 16GB RAM, 512GB SSD, 16\" WUXGA", tags: ["mới"], featured: false, bestSeller: false, showOnHome: true, specs: { CPU: "Intel Core i7-1355U", RAM: "16GB DDR5", "Màn hình": "16\" WUXGA" } },

  // PC
  { id: "p1", name: "PC Lộc An VP Core i3-12100", slug: "pc-loc-an-vp-i3", sku: "LA-PC-001", category: "pc", subcategory: "pc-van-phong", brand: "Lộc An", price: 6990000, stock: 20, status: "in_stock", image: img.pcOffice, shortDesc: "Intel Core i3-12100, 8GB RAM, 256GB SSD", tags: ["bán chạy"], featured: true, bestSeller: true, showOnHome: true, specs: { CPU: "Intel Core i3-12100", RAM: "8GB DDR4", "Ổ cứng": "256GB SSD" } },
  { id: "p2", name: "PC Lộc An VP Core i5-12400", slug: "pc-loc-an-vp-i5", sku: "LA-PC-002", category: "pc", subcategory: "pc-van-phong", brand: "Lộc An", price: 9490000, originalPrice: 10490000, discount: 10, stock: 15, status: "in_stock", image: img.pcOffice, shortDesc: "Intel Core i5-12400, 16GB RAM, 512GB SSD", tags: ["bán chạy"], featured: true, bestSeller: true, showOnHome: true, specs: { CPU: "Intel Core i5-12400", RAM: "16GB DDR4", "Ổ cứng": "512GB NVMe SSD" } },
  { id: "p3", name: "PC Lộc An VP Ryzen 5 5600G", slug: "pc-loc-an-vp-r5", sku: "LA-PC-003", category: "pc", subcategory: "pc-van-phong", brand: "Lộc An", price: 7990000, stock: 12, status: "in_stock", image: img.pcOffice, shortDesc: "AMD Ryzen 5 5600G, 8GB RAM, 256GB SSD", tags: [], featured: false, bestSeller: false, showOnHome: true, specs: { CPU: "AMD Ryzen 5 5600G", RAM: "8GB DDR4", "Ổ cứng": "256GB SSD" } },
  { id: "p4", name: "PC Lộc An Đồ Họa i7-12700", slug: "pc-loc-an-dh-i7", sku: "LA-PC-004", category: "pc", subcategory: "pc-do-hoa", brand: "Lộc An", price: 18990000, originalPrice: 20990000, discount: 10, stock: 5, status: "in_stock", image: img.pcOffice, shortDesc: "Intel Core i7-12700, RTX 3060 12GB, 32GB RAM, 1TB SSD", tags: ["mới"], featured: true, bestSeller: false, showOnHome: true, specs: { CPU: "Intel Core i7-12700", VGA: "RTX 3060 12GB", RAM: "32GB DDR4", "Ổ cứng": "1TB NVMe SSD" } },
  { id: "p5", name: "PC Lộc An Học Tập i3-10105", slug: "pc-loc-an-ht-i3", sku: "LA-PC-005", category: "pc", subcategory: "pc-hoc-tap", brand: "Lộc An", price: 4990000, stock: 25, status: "in_stock", image: img.pcOffice, shortDesc: "Intel Core i3-10105, 4GB RAM, 128GB SSD", tags: [], featured: false, bestSeller: false, showOnHome: true, specs: { CPU: "Intel Core i3-10105", RAM: "4GB DDR4", "Ổ cứng": "128GB SSD" } },
  { id: "p6", name: "PC Lộc An VP Core i5-13400", slug: "pc-loc-an-vp-i5-13", sku: "LA-PC-006", category: "pc", subcategory: "pc-van-phong", brand: "Lộc An", price: 11490000, originalPrice: 12990000, discount: 12, stock: 8, status: "in_stock", image: img.pcOffice, shortDesc: "Intel Core i5-13400, 16GB DDR5, 512GB SSD", tags: ["mới"], featured: false, bestSeller: false, showOnHome: true, specs: { CPU: "Intel Core i5-13400", RAM: "16GB DDR5", "Ổ cứng": "512GB SSD" } },
  { id: "p7", name: "PC Lộc An VP Ryzen 7 5700G", slug: "pc-loc-an-vp-r7", sku: "LA-PC-007", category: "pc", subcategory: "pc-van-phong", brand: "Lộc An", price: 10990000, stock: 6, status: "in_stock", image: img.pcOffice, shortDesc: "AMD Ryzen 7 5700G, 16GB RAM, 512GB SSD", tags: [], featured: false, bestSeller: false, showOnHome: true, specs: { CPU: "AMD Ryzen 7 5700G", RAM: "16GB DDR4", "Ổ cứng": "512GB SSD" } },
  { id: "p8", name: "PC Lộc An Workstation i9-13900", slug: "pc-loc-an-ws-i9", sku: "LA-PC-008", category: "pc", subcategory: "pc-workstation", brand: "Lộc An", price: 35990000, stock: 2, status: "in_stock", image: img.pcOffice, shortDesc: "Intel Core i9-13900, RTX 4070 12GB, 64GB DDR5, 2TB SSD", tags: ["mới"], featured: true, bestSeller: false, showOnHome: true, specs: { CPU: "Intel Core i9-13900", VGA: "RTX 4070 12GB", RAM: "64GB DDR5", "Ổ cứng": "2TB NVMe SSD" } },
  { id: "p9", name: "PC Lộc An Kế Toán i5-12400", slug: "pc-loc-an-kt-i5", sku: "LA-PC-009", category: "pc", subcategory: "pc-van-phong", brand: "Lộc An", price: 8490000, stock: 10, status: "in_stock", image: img.pcOffice, shortDesc: "Intel Core i5-12400, 8GB RAM, 512GB SSD, Win 11 Pro", tags: [], featured: false, bestSeller: true, showOnHome: true, specs: { CPU: "Intel Core i5-12400", RAM: "8GB DDR4", "Ổ cứng": "512GB SSD", OS: "Windows 11 Pro" } },
  { id: "p10", name: "PC Lộc An Đồ Họa R7-5800X", slug: "pc-loc-an-dh-r7", sku: "LA-PC-010", category: "pc", subcategory: "pc-do-hoa", brand: "Lộc An", price: 22990000, originalPrice: 24990000, discount: 8, stock: 3, status: "in_stock", image: img.pcOffice, shortDesc: "AMD Ryzen 7 5800X, RTX 3070 8GB, 32GB RAM, 1TB SSD", tags: ["giảm giá"], featured: false, bestSeller: false, showOnHome: true, specs: { CPU: "AMD Ryzen 7 5800X", VGA: "RTX 3070 8GB", RAM: "32GB DDR4" } },

  // PC GAMING
  { id: "g1", name: "PC Gaming Lộc An Storm i5-12400F/RTX 3060", slug: "pc-gaming-storm-i5-3060", sku: "LA-PG-001", category: "pc-gaming", subcategory: "pc-gaming-pho-thong", brand: "Lộc An", price: 14990000, originalPrice: 16990000, discount: 12, stock: 10, status: "in_stock", image: img.pcGaming, shortDesc: "Intel Core i5-12400F, RTX 3060 12GB, 16GB DDR4, 512GB SSD", tags: ["bán chạy", "giảm giá"], featured: true, bestSeller: true, showOnHome: true, specs: { CPU: "Intel Core i5-12400F", VGA: "RTX 3060 12GB", RAM: "16GB DDR4", "Ổ cứng": "512GB NVMe SSD" } },
  { id: "g2", name: "PC Gaming Lộc An Thunder i5-13400F/RTX 4060", slug: "pc-gaming-thunder-i5-4060", sku: "LA-PG-002", category: "pc-gaming", subcategory: "pc-gaming-tam-trung", brand: "Lộc An", price: 19990000, originalPrice: 22490000, discount: 11, stock: 7, status: "in_stock", image: img.pcGaming, shortDesc: "Intel Core i5-13400F, RTX 4060 8GB, 16GB DDR5, 512GB SSD", tags: ["bán chạy"], featured: true, bestSeller: true, showOnHome: true, specs: { CPU: "Intel Core i5-13400F", VGA: "RTX 4060 8GB", RAM: "16GB DDR5" } },
  { id: "g3", name: "PC Gaming Lộc An Titan i7-13700F/RTX 4070", slug: "pc-gaming-titan-i7-4070", sku: "LA-PG-003", category: "pc-gaming", subcategory: "pc-gaming-cao-cap", brand: "Lộc An", price: 29990000, originalPrice: 32990000, discount: 9, stock: 4, status: "in_stock", image: img.pcGaming, shortDesc: "Intel Core i7-13700F, RTX 4070 12GB, 32GB DDR5, 1TB SSD", tags: ["mới"], featured: true, bestSeller: false, showOnHome: true, specs: { CPU: "Intel Core i7-13700F", VGA: "RTX 4070 12GB", RAM: "32GB DDR5", "Ổ cứng": "1TB NVMe SSD" } },
  { id: "g4", name: "PC Gaming Lộc An R5/RX 7600", slug: "pc-gaming-r5-rx7600", sku: "LA-PG-004", category: "pc-gaming", subcategory: "pc-gaming-pho-thong", brand: "Lộc An", price: 13490000, stock: 8, status: "in_stock", image: img.pcGaming, shortDesc: "AMD Ryzen 5 5600, RX 7600 8GB, 16GB DDR4, 512GB SSD", tags: [], featured: false, bestSeller: false, showOnHome: true, specs: { CPU: "AMD Ryzen 5 5600", VGA: "RX 7600 8GB", RAM: "16GB DDR4" } },
  { id: "g5", name: "PC Gaming Lộc An Ultra i7-14700F/RTX 4070 Ti", slug: "pc-gaming-ultra-i7-4070ti", sku: "LA-PG-005", category: "pc-gaming", subcategory: "pc-gaming-cao-cap", brand: "Lộc An", price: 38990000, originalPrice: 42990000, discount: 9, stock: 2, status: "in_stock", image: img.pcGaming, shortDesc: "Intel Core i7-14700F, RTX 4070 Ti 12GB, 32GB DDR5, 1TB SSD", tags: ["mới"], featured: true, bestSeller: false, showOnHome: true, specs: { CPU: "Intel Core i7-14700F", VGA: "RTX 4070 Ti 12GB", RAM: "32GB DDR5" } },
  { id: "g6", name: "PC Gaming Lộc An Flash i5/RTX 4050", slug: "pc-gaming-flash-i5-4050", sku: "LA-PG-006", category: "pc-gaming", subcategory: "pc-gaming-pho-thong", brand: "Lộc An", price: 15990000, stock: 6, status: "in_stock", image: img.pcGaming, shortDesc: "Intel Core i5-12400F, RTX 4050 6GB, 16GB DDR4, 512GB SSD", tags: [], featured: false, bestSeller: true, showOnHome: true, specs: { CPU: "Intel Core i5-12400F", VGA: "RTX 4050 6GB", RAM: "16GB DDR4" } },
  { id: "g7", name: "PC Gaming Lộc An Stream R7/RTX 4060", slug: "pc-gaming-stream-r7-4060", sku: "LA-PG-007", category: "pc-gaming", subcategory: "pc-livestream", brand: "Lộc An", price: 23990000, originalPrice: 25990000, discount: 8, stock: 3, status: "in_stock", image: img.pcGaming, shortDesc: "AMD Ryzen 7 5800X3D, RTX 4060 8GB, 32GB DDR4, 1TB SSD", tags: ["giảm giá"], featured: false, bestSeller: false, showOnHome: true, specs: { CPU: "AMD Ryzen 7 5800X3D", VGA: "RTX 4060 8GB", RAM: "32GB DDR4" } },
  { id: "g8", name: "PC Gaming Lộc An Bolt i5-13400F/RTX 3060", slug: "pc-gaming-bolt-i5-3060", sku: "LA-PG-008", category: "pc-gaming", subcategory: "pc-gaming-pho-thong", brand: "Lộc An", price: 13990000, originalPrice: 15490000, discount: 10, stock: 12, status: "in_stock", image: img.pcGaming, shortDesc: "Intel Core i5-13400F, RTX 3060 12GB, 16GB DDR4, 512GB SSD", tags: ["bán chạy"], featured: false, bestSeller: true, showOnHome: true, specs: { CPU: "Intel Core i5-13400F", VGA: "RTX 3060 12GB" } },
  { id: "g9", name: "PC Gaming Lộc An R5/RTX 4060 Ti", slug: "pc-gaming-r5-4060ti", sku: "LA-PG-009", category: "pc-gaming", subcategory: "pc-gaming-tam-trung", brand: "Lộc An", price: 22490000, stock: 5, status: "in_stock", image: img.pcGaming, shortDesc: "AMD Ryzen 5 7600, RTX 4060 Ti 8GB, 16GB DDR5, 1TB SSD", tags: ["mới"], featured: false, bestSeller: false, showOnHome: true, specs: { CPU: "AMD Ryzen 5 7600", VGA: "RTX 4060 Ti 8GB" } },
  { id: "g10", name: "PC Gaming Lộc An Supreme i9/RTX 4080", slug: "pc-gaming-supreme-i9-4080", sku: "LA-PG-010", category: "pc-gaming", subcategory: "pc-gaming-cao-cap", brand: "Lộc An", price: 55990000, stock: 1, status: "in_stock", image: img.pcGaming, shortDesc: "Intel Core i9-14900K, RTX 4080 16GB, 64GB DDR5, 2TB SSD", tags: ["mới"], featured: true, bestSeller: false, showOnHome: true, specs: { CPU: "Intel Core i9-14900K", VGA: "RTX 4080 16GB", RAM: "64GB DDR5" } },

  // LINH KIEN
  { id: "lk1", name: "CPU Intel Core i5-12400F", slug: "cpu-i5-12400f", sku: "LA-LK-001", category: "linh-kien", subcategory: "cpu", brand: "Intel", price: 2990000, originalPrice: 3490000, discount: 14, stock: 30, status: "in_stock", image: img.cpu, shortDesc: "6 nhân 12 luồng, 2.5GHz - 4.4GHz, Socket LGA 1700", tags: ["bán chạy"], featured: false, bestSeller: true, showOnHome: true, specs: { "Số nhân": "6 nhân 12 luồng", "Xung nhịp": "2.5 - 4.4 GHz", Socket: "LGA 1700" } },
  { id: "lk2", name: "RAM Kingston Fury Beast 16GB DDR4 3200MHz", slug: "ram-kingston-fury-16gb", sku: "LA-LK-002", category: "linh-kien", subcategory: "ram", brand: "Kingston", price: 890000, stock: 50, status: "in_stock", image: img.ram, shortDesc: "16GB DDR4, Bus 3200MHz, Heatsink", tags: ["bán chạy"], featured: false, bestSeller: true, showOnHome: true, specs: { "Dung lượng": "16GB", Loại: "DDR4", Bus: "3200MHz" } },
  { id: "lk3", name: "SSD Samsung 980 Pro 1TB NVMe M.2", slug: "ssd-samsung-980-pro-1tb", sku: "LA-LK-003", category: "linh-kien", subcategory: "ssd", brand: "Samsung", price: 2490000, originalPrice: 2990000, discount: 17, stock: 20, status: "in_stock", image: img.ssd, shortDesc: "1TB, NVMe M.2 2280, Đọc 7000MB/s, Ghi 5000MB/s", tags: ["giảm giá"], featured: false, bestSeller: true, showOnHome: true, specs: { "Dung lượng": "1TB", "Giao tiếp": "NVMe M.2 2280", "Tốc độ đọc": "7000 MB/s" } },
  { id: "lk4", name: "VGA GIGABYTE RTX 4060 Eagle OC 8GB", slug: "vga-rtx-4060-eagle-oc", sku: "LA-LK-004", category: "linh-kien", subcategory: "vga", brand: "Gigabyte", price: 7990000, originalPrice: 8990000, discount: 11, stock: 8, status: "in_stock", image: img.vga, shortDesc: "8GB GDDR6, CUDA 3072, Boost Clock 2535MHz", tags: ["mới"], featured: true, bestSeller: false, showOnHome: true, specs: { VRAM: "8GB GDDR6", CUDA: "3072 cores", "Boost Clock": "2535 MHz" } },
  { id: "lk5", name: "Mainboard ASUS PRIME B660M-A D4", slug: "mainboard-asus-prime-b660m", sku: "LA-LK-005", category: "linh-kien", subcategory: "mainboard", brand: "ASUS", price: 2490000, stock: 15, status: "in_stock", image: img.mainboard, shortDesc: "Intel B660, LGA 1700, DDR4, M.2, mATX", tags: [], featured: false, bestSeller: false, showOnHome: true, specs: { Chipset: "Intel B660", Socket: "LGA 1700", RAM: "DDR4, 4 slot" } },
  { id: "lk6", name: "Nguồn Corsair CV650 650W 80+ Bronze", slug: "nguon-corsair-cv650", sku: "LA-LK-006", category: "linh-kien", subcategory: "psu", brand: "Corsair", price: 1290000, stock: 25, status: "in_stock", image: img.psu, shortDesc: "650W, 80+ Bronze, Non-modular", tags: ["bán chạy"], featured: false, bestSeller: true, showOnHome: true, specs: { "Công suất": "650W", "Chứng chỉ": "80+ Bronze" } },
  { id: "lk7", name: "Case NZXT H5 Flow", slug: "case-nzxt-h5-flow", sku: "LA-LK-007", category: "linh-kien", subcategory: "case", brand: "NZXT", price: 2190000, stock: 10, status: "in_stock", image: img.pcCase, shortDesc: "Mid Tower, ATX, Tempered Glass, Airflow", tags: ["mới"], featured: false, bestSeller: false, showOnHome: true, specs: { "Form Factor": "Mid Tower", "Hỗ trợ": "ATX / mATX / ITX" } },
  { id: "lk8", name: "Tản nhiệt DeepCool AK400", slug: "tan-nhiet-deepcool-ak400", sku: "LA-LK-008", category: "linh-kien", subcategory: "tan-nhiet", brand: "DeepCool", price: 590000, stock: 30, status: "in_stock", image: img.cpu, shortDesc: "Tower cooler, 4 ống đồng, TDP 220W, quạt 120mm", tags: ["bán chạy"], featured: false, bestSeller: true, showOnHome: true, specs: { TDP: "220W", "Quạt": "120mm", "Ống đồng": "4 ống" } },
  { id: "lk9", name: "CPU AMD Ryzen 5 5600X", slug: "cpu-r5-5600x", sku: "LA-LK-009", category: "linh-kien", subcategory: "cpu", brand: "AMD", price: 3290000, originalPrice: 3890000, discount: 15, stock: 18, status: "in_stock", image: img.cpu, shortDesc: "6 nhân 12 luồng, 3.7GHz - 4.6GHz, Socket AM4", tags: ["giảm giá"], featured: false, bestSeller: false, showOnHome: true, specs: { "Số nhân": "6C/12T", "Xung nhịp": "3.7 - 4.6 GHz", Socket: "AM4" } },
  { id: "lk10", name: "RAM Corsair Vengeance 16GB DDR5 5600MHz", slug: "ram-corsair-ddr5-16gb", sku: "LA-LK-010", category: "linh-kien", subcategory: "ram", brand: "Corsair", price: 1390000, stock: 20, status: "in_stock", image: img.ram, shortDesc: "16GB DDR5, Bus 5600MHz", tags: ["mới"], featured: false, bestSeller: false, showOnHome: true, specs: { "Dung lượng": "16GB", Loại: "DDR5", Bus: "5600MHz" } },
  { id: "lk11", name: "HDD Seagate BarraCuda 2TB", slug: "hdd-seagate-2tb", sku: "LA-LK-011", category: "linh-kien", subcategory: "hdd", brand: "Seagate", price: 1190000, stock: 35, status: "in_stock", image: img.ssd, shortDesc: "2TB, 7200RPM, SATA3, 256MB Cache", tags: [], featured: false, bestSeller: false, showOnHome: true, specs: { "Dung lượng": "2TB", "Tốc độ quay": "7200 RPM" } },
  { id: "lk12", name: "VGA MSI RTX 4070 Ventus 2X OC 12GB", slug: "vga-msi-rtx-4070", sku: "LA-LK-012", category: "linh-kien", subcategory: "vga", brand: "MSI", price: 13990000, originalPrice: 15490000, discount: 10, stock: 4, status: "in_stock", image: img.vga, shortDesc: "12GB GDDR6X, CUDA 5888, Boost Clock 2475MHz", tags: ["giảm giá"], featured: true, bestSeller: false, showOnHome: true, specs: { VRAM: "12GB GDDR6X", CUDA: "5888 cores" } },

  // THIET BI MANG
  { id: "m1", name: "Router WiFi 6 TP-Link AX1500", slug: "router-tplink-ax1500", sku: "LA-TBM-001", category: "thiet-bi-mang", subcategory: "router-wifi", brand: "TP-Link", price: 890000, originalPrice: 1090000, discount: 18, stock: 20, status: "in_stock", image: img.router, shortDesc: "WiFi 6 AX1500, 4 ăng-ten, Gigabit", tags: ["bán chạy", "giảm giá"], featured: false, bestSeller: true, showOnHome: true, specs: { "Chuẩn WiFi": "WiFi 6 (802.11ax)", "Tốc độ": "1500Mbps" } },
  { id: "m2", name: "Mesh WiFi TP-Link Deco M4 (3-pack)", slug: "mesh-tplink-deco-m4", sku: "LA-TBM-002", category: "thiet-bi-mang", subcategory: "mesh-wifi", brand: "TP-Link", price: 2490000, stock: 10, status: "in_stock", image: img.router, shortDesc: "Mesh WiFi AC1200, phủ 370m², 3 bộ", tags: [], featured: false, bestSeller: false, showOnHome: true, specs: { "Phủ sóng": "370m²", "Chuẩn WiFi": "AC1200" } },
  { id: "m3", name: "Switch TP-Link 8 cổng Gigabit TL-SG108", slug: "switch-tplink-8port", sku: "LA-TBM-003", category: "thiet-bi-mang", subcategory: "switch", brand: "TP-Link", price: 390000, stock: 30, status: "in_stock", image: img.switchImg, shortDesc: "8 cổng RJ45 Gigabit, vỏ kim loại", tags: ["bán chạy"], featured: false, bestSeller: true, showOnHome: true, specs: { "Số cổng": "8 x Gigabit", "Vật liệu": "Vỏ kim loại" } },
  { id: "m4", name: "Router WiFi 6 ASUS RT-AX55", slug: "router-asus-ax55", sku: "LA-TBM-004", category: "thiet-bi-mang", subcategory: "router-wifi", brand: "ASUS", price: 1490000, originalPrice: 1790000, discount: 17, stock: 12, status: "in_stock", image: img.router, shortDesc: "WiFi 6 AX1800, AiMesh, AiProtection", tags: ["giảm giá"], featured: false, bestSeller: false, showOnHome: true, specs: { "Chuẩn WiFi": "WiFi 6 AX1800" } },
  { id: "m5", name: "Access Point UniFi U6 Lite", slug: "ap-unifi-u6-lite", sku: "LA-TBM-005", category: "thiet-bi-mang", subcategory: "access-point", brand: "Ubiquiti", price: 2290000, stock: 8, status: "in_stock", image: img.router, shortDesc: "WiFi 6, PoE, phù hợp văn phòng / quán cafe", tags: ["mới"], featured: false, bestSeller: false, showOnHome: true, specs: { "Chuẩn WiFi": "WiFi 6", "Nguồn": "PoE 802.3af" } },
  { id: "m6", name: "Mesh WiFi ASUS ZenWiFi AX Mini (2-pack)", slug: "mesh-asus-zenwifi-mini", sku: "LA-TBM-006", category: "thiet-bi-mang", subcategory: "mesh-wifi", brand: "ASUS", price: 3290000, stock: 5, status: "in_stock", image: img.router, shortDesc: "WiFi 6 AX1800, phủ 280m², 2 bộ", tags: [], featured: false, bestSeller: false, showOnHome: true, specs: { "Phủ sóng": "280m²", "Chuẩn WiFi": "WiFi 6 AX1800" } },

  // CAMERA
  { id: "c1", name: "Camera IP Hikvision DS-2CD1047G2-L 4MP", slug: "camera-hikvision-4mp", sku: "LA-CAM-001", category: "camera", subcategory: "camera-ngoai-troi", brand: "Hikvision", price: 990000, originalPrice: 1190000, discount: 17, stock: 25, status: "in_stock", image: img.cameraOutdoor, shortDesc: "4MP, Full Color, IP67, PoE", tags: ["bán chạy", "giảm giá"], featured: false, bestSeller: true, showOnHome: true, specs: { "Độ phân giải": "4MP", "Tầm nhìn": "Full Color", "Chống nước": "IP67" } },
  { id: "c2", name: "Camera WiFi Imou Bullet 2E 4MP", slug: "camera-imou-bullet-2e", sku: "LA-CAM-002", category: "camera", subcategory: "camera-ngoai-troi", brand: "Imou", price: 690000, stock: 30, status: "in_stock", image: img.cameraOutdoor, shortDesc: "4MP, WiFi, Full Color, IP67, đàm thoại 2 chiều", tags: ["bán chạy"], featured: false, bestSeller: true, showOnHome: true, specs: { "Độ phân giải": "4MP", "Kết nối": "WiFi", "Chống nước": "IP67" } },
  { id: "c3", name: "Combo 4 Camera Hikvision 2MP + Đầu ghi", slug: "combo-4-camera-hikvision", sku: "LA-CAM-003", category: "camera", subcategory: "combo-camera", brand: "Hikvision", price: 3990000, originalPrice: 4990000, discount: 20, stock: 10, status: "in_stock", image: img.camera, shortDesc: "4 camera 2MP + đầu ghi 4 kênh + HDD 500GB + phụ kiện", tags: ["giảm giá", "bán chạy"], featured: true, bestSeller: true, showOnHome: true, specs: { "Camera": "4 x 2MP", "Đầu ghi": "4 kênh", "HDD": "500GB" } },
  { id: "c4", name: "Camera trong nhà Imou Ranger 2C 4MP", slug: "camera-imou-ranger-2c", sku: "LA-CAM-004", category: "camera", subcategory: "camera-trong-nha", brand: "Imou", price: 590000, stock: 40, status: "in_stock", image: img.camera, shortDesc: "4MP, WiFi, xoay 360°, đàm thoại 2 chiều", tags: ["bán chạy"], featured: false, bestSeller: true, showOnHome: true, specs: { "Độ phân giải": "4MP", "Góc quay": "360°", "Kết nối": "WiFi" } },
  { id: "c5", name: "Đầu ghi Hikvision 8 kênh DS-7108NI-K1", slug: "dau-ghi-hikvision-8-kenh", sku: "LA-CAM-005", category: "camera", subcategory: "dau-ghi", brand: "Hikvision", price: 1890000, stock: 12, status: "in_stock", image: img.camera, shortDesc: "8 kênh IP, hỗ trợ 6MP, 1 khe HDD", tags: [], featured: false, bestSeller: false, showOnHome: true, specs: { "Số kênh": "8 kênh IP", "Độ phân giải tối đa": "6MP" } },
  { id: "c6", name: "Combo 8 Camera Dahua 2MP Full Color", slug: "combo-8-camera-dahua", sku: "LA-CAM-006", category: "camera", subcategory: "combo-camera", brand: "Dahua", price: 7990000, originalPrice: 9490000, discount: 16, stock: 5, status: "in_stock", image: img.camera, shortDesc: "8 camera 2MP Full Color + đầu ghi 8 kênh + HDD 1TB + phụ kiện", tags: ["giảm giá"], featured: true, bestSeller: false, showOnHome: true, specs: { "Camera": "8 x 2MP Full Color", "Đầu ghi": "8 kênh", "HDD": "1TB" } },

  // MÀN HÌNH
  { id: "mh1", name: "Màn hình Dell S2422HG 24\" 165Hz", slug: "man-hinh-dell-s2422hg", sku: "LA-MH-001", category: "man-hinh", subcategory: "man-hinh-gaming", brand: "Dell", price: 3490000, originalPrice: 3990000, discount: 13, stock: 12, status: "in_stock", image: img.monitorGaming, shortDesc: "24\" FHD, VA, 165Hz, 1ms, Curved, FreeSync", tags: ["bán chạy", "giảm giá"], featured: true, bestSeller: true, showOnHome: true, specs: { "Kích thước": "24 inch", "Tấm nền": "VA Curved", "Tần số": "165Hz", "Thời gian phản hồi": "1ms" } },
  { id: "mh2", name: "Màn hình LG 24MP400 24\" IPS", slug: "man-hinh-lg-24mp400", sku: "LA-MH-002", category: "man-hinh", subcategory: "man-hinh-van-phong", brand: "LG", price: 2490000, stock: 20, status: "in_stock", image: img.monitor, shortDesc: "24\" FHD, IPS, 75Hz, FreeSync, viền mỏng", tags: ["bán chạy"], featured: false, bestSeller: true, showOnHome: true, specs: { "Kích thước": "24 inch", "Tấm nền": "IPS", "Tần số": "75Hz" } },
  { id: "mh3", name: "Màn hình ASUS VG249Q1A 24\" 165Hz", slug: "man-hinh-asus-vg249q1a", sku: "LA-MH-003", category: "man-hinh", subcategory: "man-hinh-gaming", brand: "ASUS", price: 3990000, stock: 8, status: "in_stock", image: img.monitorGaming, shortDesc: "24\" FHD, IPS, 165Hz, 1ms, FreeSync Premium", tags: ["mới"], featured: true, bestSeller: false, showOnHome: true, specs: { "Kích thước": "24 inch", "Tấm nền": "IPS", "Tần số": "165Hz" } },
  { id: "mh4", name: "Màn hình Samsung LS27C310 27\" IPS", slug: "man-hinh-samsung-27c310", sku: "LA-MH-004", category: "man-hinh", subcategory: "man-hinh-van-phong", brand: "Samsung", price: 3290000, originalPrice: 3790000, discount: 13, stock: 15, status: "in_stock", image: img.monitor, shortDesc: "27\" FHD, IPS, 75Hz, viền mỏng 3 cạnh", tags: ["giảm giá"], featured: false, bestSeller: false, showOnHome: true, specs: { "Kích thước": "27 inch", "Tấm nền": "IPS", "Tần số": "75Hz" } },
  { id: "mh5", name: "Màn hình MSI G274F 27\" 180Hz", slug: "man-hinh-msi-g274f", sku: "LA-MH-005", category: "man-hinh", subcategory: "man-hinh-gaming", brand: "MSI", price: 4990000, stock: 6, status: "in_stock", image: img.monitorGaming, shortDesc: "27\" FHD, Rapid IPS, 180Hz, 1ms, G-Sync Compatible", tags: ["mới"], featured: true, bestSeller: false, showOnHome: true, specs: { "Kích thước": "27 inch", "Tấm nền": "Rapid IPS", "Tần số": "180Hz" } },
  { id: "mh6", name: "Màn hình HP M24f 24\" IPS", slug: "man-hinh-hp-m24f", sku: "LA-MH-006", category: "man-hinh", subcategory: "man-hinh-van-phong", brand: "HP", price: 2290000, stock: 18, status: "in_stock", image: img.monitor, shortDesc: "24\" FHD, IPS, 75Hz, chống chói", tags: [], featured: false, bestSeller: true, showOnHome: true, specs: { "Kích thước": "24 inch", "Tấm nền": "IPS", "Tần số": "75Hz" } },

  // PHỤ KIỆN NGOẠI VI
  { id: "nv1", name: "Bàn phím cơ Akko 3068B Plus", slug: "ban-phim-akko-3068b", sku: "LA-NV-001", category: "ngoai-vi", subcategory: "ban-phim", brand: "Akko", price: 1290000, originalPrice: 1490000, discount: 13, stock: 15, status: "in_stock", image: img.keyboard, shortDesc: "68 phím, Bluetooth/USB-C, Hot-swap, RGB", tags: ["bán chạy", "giảm giá"], featured: false, bestSeller: true, showOnHome: true, specs: { "Layout": "68 phím", "Kết nối": "Bluetooth 5.0 / USB-C", "Switch": "Hot-swap" } },
  { id: "nv2", name: "Chuột Logitech G304 Wireless", slug: "chuot-logitech-g304", sku: "LA-NV-002", category: "ngoai-vi", subcategory: "chuot", brand: "Logitech", price: 690000, stock: 25, status: "in_stock", image: img.mouse, shortDesc: "Wireless LIGHTSPEED, 12000 DPI, pin AA 250 giờ", tags: ["bán chạy"], featured: false, bestSeller: true, showOnHome: true, specs: { "Cảm biến": "HERO 12K", "Kết nối": "LIGHTSPEED Wireless", "Pin": "250 giờ" } },
  { id: "nv3", name: "Tai nghe HyperX Cloud Stinger 2", slug: "tai-nghe-hyperx-stinger-2", sku: "LA-NV-003", category: "ngoai-vi", subcategory: "tai-nghe", brand: "HyperX", price: 990000, originalPrice: 1190000, discount: 17, stock: 10, status: "in_stock", image: img.headset, shortDesc: "Over-ear, DTS Headphone:X, mic xoay, đệm tai êm", tags: ["giảm giá"], featured: false, bestSeller: false, showOnHome: true, specs: { "Driver": "50mm", "Kết nối": "3.5mm", "Micro": "Có, xoay được" } },
  { id: "nv4", name: "Webcam Logitech C920 HD Pro", slug: "webcam-logitech-c920", sku: "LA-NV-004", category: "ngoai-vi", subcategory: "webcam", brand: "Logitech", price: 1590000, stock: 8, status: "in_stock", image: img.camera, shortDesc: "Full HD 1080p, auto focus, 2 mic stereo", tags: [], featured: false, bestSeller: false, showOnHome: true, specs: { "Độ phân giải": "1080p/30fps", "Lấy nét": "Tự động", "Micro": "2 mic stereo" } },
  { id: "nv5", name: "Chuột Razer DeathAdder V3", slug: "chuot-razer-deathadder-v3", sku: "LA-NV-005", category: "ngoai-vi", subcategory: "chuot", brand: "Razer", price: 1490000, stock: 12, status: "in_stock", image: img.mouse, shortDesc: "Focus Pro 30K, 59g siêu nhẹ, HyperSpeed Wireless", tags: ["mới"], featured: true, bestSeller: false, showOnHome: true, specs: { "Cảm biến": "Focus Pro 30K", "Trọng lượng": "59g", "Kết nối": "HyperSpeed Wireless" } },
  { id: "nv6", name: "Bàn phím Rapoo V500PRO", slug: "ban-phim-rapoo-v500pro", sku: "LA-NV-006", category: "ngoai-vi", subcategory: "ban-phim", brand: "Rapoo", price: 490000, stock: 30, status: "in_stock", image: img.keyboard, shortDesc: "Bàn phím cơ, 104 phím, USB, LED rainbow", tags: ["bán chạy"], featured: false, bestSeller: true, showOnHome: true, specs: { "Layout": "104 phím Full-size", "Kết nối": "USB", "LED": "Rainbow" } },
];

// KEY phải trùng với AdminProductsPage
const STORAGE_KEY = "admin_products";

function getStoredProducts(): Product[] {
  try {
    const stored = localStorage.getItem(STORAGE_KEY);
    return stored ? JSON.parse(stored) : defaultProducts;
  } catch {
    return defaultProducts;
  }
}

// Export như một getter - mỗi lần gọi sẽ đọc từ localStorage
export const products: Product[] = getStoredProducts();

// Hàm helper - dùng trong các trang
export function getAllProducts(): Product[] {
  return getStoredProducts();
}

export function formatPrice(price: number): string {
  return new Intl.NumberFormat("vi-VN").format(price) + "₫";
}

export function getProductsByCategory(cat: string): Product[] {
  return getStoredProducts().filter(p => p.category === cat && p.showOnHome);
}

export function getAllProductsByCategory(cat: string): Product[] {
  return getStoredProducts().filter(p => p.category === cat);
}

export function getFeaturedProducts(): Product[] {
  return getStoredProducts().filter(p => p.featured);
}

export function getBestSellers(): Product[] {
  return getStoredProducts().filter(p => p.bestSeller);
}

export function getSaleProducts(): Product[] {
  return getStoredProducts().filter(p => p.discount && p.discount > 0);
}

export function getProductBrands(cat: string): string[] {
  const brands = getStoredProducts().filter(p => p.category === cat).map(p => p.brand);
  return [...new Set(brands)];
}
